<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast5Articles()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.dateParution', 'DESC')
            ->getQuery()
            ->setMaxResults(5)
            ->getResult();
    }

    public function findAllByDate()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.dateParution', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
