# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:



    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_provider:
            entity:
                class: AppBundle:User
                property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                default_target_path: admin
            provider : database_provider
            logout:
                path: /logout
                target: login



            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }


